baseurl = "/"
languageCode = "en-us"
title = "A byte of learning"
theme = "hugo-xmin"
author = "SN248"
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    url = "/post/"
  [[menu.main]]
    name = "Categories"
    weight = 3
    url = "/categories/"
  [[menu.main]]
    name = "Tags"
    weight = 4
    url = "/tags/"
  [[menu.main]]
    name = "Contact"
    weight = 5
    url = "/contact/"
  [[menu.main]]
    name = "Subscribe"
    weight = 6
    url = "/index.xml"
    
[params]
    description = "A blog of SN248"
    footer = "&copy; SN248 2017 -- 2020 | [Github](https://github.com/sn248) | [LinkedIn](https://www.linkedin.com/in/satyaprakashnayak/) "

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
