baseurl = "https://sn248.rbind.io/"
languageCode = "en-us"
title = "A byte of learning"
theme = "hugo-ivy"
author = "SN248"
#canonifyurls = true
#paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Contact"
    weight = 5
    url = "/contact/"
  [[menu.main]]
    name = "Subscribe"
    weight = 6
    url = "/index.xml"
    
[params]
    description = "A blog of SN248"
    footer = "&copy; SN248 2017 -- 2020 | [Github](https://github.com/sn248) | [LinkedIn](https://www.linkedin.com/in/satyaprakashnayak/) "

highlightjsVersion = "9.12.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"